### ISSUE TITLE
Does not seem to work with Sphinx 1.6

### ISSUE THREAD

**Issue by romaninsh** [markstory/sphinxcontrib-phpdomain#13]
Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/environment/__init__.py", line 304, in warn
    self._warnfunc(msg, (docname, lineno), **kwargs)
TypeError: 'NoneType' object is not callable

```
# Sphinx version: 1.6.2
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   loading intersphinx inventory from http://docs.python.org/objects.inv...
#   intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 17 source files that are out of date
#   updating environment:
#   17 added, 0 changed, 0 removed
#   reading sources... [  5%] advanced
#   reading sources... [ 11%] conditions
#   reading sources... [ 17%] design
#   reading sources... [ 23%] expressions
# Loaded extensions:
#   sphinx.ext.coverage (1.6.2) from /usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/ext/coverage.pyc
#   sphinxcontrib.phpdomain (unknown version) from /usr/local/lib/python2.7/site-packages/sphinxcontrib_phpdomain-0.2.5-py2.7.egg/sphinxcontrib/phpdomain.pyc
#   sphinx.ext.todo (1.6.2) from /usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.6.2) from /usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.6.2) from /usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/ext/intersphinx.pyc
#   alabaster (0.7.9) from /usr/local/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/environment/__init__.py", line 724, in read_doc
    pub.publish()
  File "/usr/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/io.py", line 74, in read
    self.parse()
  File "/usr/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2980, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/domains/__init__.py", line 218, in run
    return BaseDirective.run(self)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/directives/__init__.py", line 171, in run
    self.add_target_and_index(name, sig, signode)
  File "/usr/local/lib/python2.7/site-packages/sphinxcontrib_phpdomain-0.2.5-py2.7.egg/sphinxcontrib/phpdomain.py", line 282, in add_target_and_index
    self.lineno)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/environment/__init__.py", line 304, in warn
    self._warnfunc(msg, (docname, lineno), **kwargs)
TypeError: 'NoneType' object is not callable
```

**Comment by markstory** [comment]
What does your source document look like?

**Comment by markstory** [comment]
I'm not able to reproduce this with Sphinx 1.6.4. The test documents generate, and so do the other documentation projects I have with sphinx.
